# Generated by Django 4.2 on 2023-04-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='event_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
