# Generated by Django 4.2 on 2023-04-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='event_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
