# Generated by Django 3.2.8 on 2023-04-07 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_reserveration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='reserveration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.reservation'),
        ),
    ]
