# Generated by Django 3.2.8 on 2023-04-07 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_reserveration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='reserveration',
        ),
        migrations.AddField(
            model_name='room',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.reservation'),
        ),
    ]
