# Generated by Django 3.2.8 on 2023-07-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PolyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=15, verbose_name='email address')),
                ('rcs', models.CharField(max_length=10, unique=True)),
                ('rin', models.CharField(max_length=9)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('roles', models.ManyToManyField(to='users.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
