# Generated by Django 3.2.8 on 2023-07-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230713_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polyuser',
            name='rin',
            field=models.CharField(max_length=9),
        ),
    ]
