# Generated by Django 3.2.8 on 2023-07-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_polyuser_rin'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyuser',
            name='is_rpi_staff',
            field=models.BooleanField(default=False),
        ),
    ]
