# Generated by Django 3.2.8 on 2023-07-20 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(default='', max_length=30)),
                ('num_floors', models.IntegerField(default=0)),
                ('reservations_hidden', models.BooleanField(blank=True, default=False)),
                ('force_hidden', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_num', models.CharField(default='', max_length=5)),
                ('num_rooms', models.IntegerField(default=0)),
                ('color', models.CharField(default='#FF8C00', max_length=7)),
                ('reservations_hidden', models.BooleanField(blank=True, default=False)),
                ('force_hidden', models.BooleanField(blank=True, default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floors.building')),
                ('roles', models.ManyToManyField(blank=True, to='users.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField(blank=True, null=True)),
                ('monday_end', models.TimeField(blank=True, null=True)),
                ('tuesday_start', models.TimeField(blank=True, null=True)),
                ('tuesday_end', models.TimeField(blank=True, null=True)),
                ('wednesday_start', models.TimeField(blank=True, null=True)),
                ('wednesday_end', models.TimeField(blank=True, null=True)),
                ('thursday_start', models.TimeField(blank=True, null=True)),
                ('thursday_end', models.TimeField(blank=True, null=True)),
                ('friday_start', models.TimeField(blank=True, null=True)),
                ('friday_end', models.TimeField(blank=True, null=True)),
                ('saturday_start', models.TimeField(blank=True, null=True)),
                ('saturday_end', models.TimeField(blank=True, null=True)),
                ('sunday_start', models.TimeField(blank=True, null=True)),
                ('sunday_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=5)),
                ('closed', models.BooleanField(blank=True, default=False)),
                ('reservations_hidden', models.BooleanField(blank=True, default=False)),
                ('force_hidden', models.BooleanField(blank=True, default=False)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floors.floor')),
                ('roles', models.ManyToManyField(blank=True, to='users.Role')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floors.hours'),
        ),
        migrations.AddField(
            model_name='building',
            name='roles',
            field=models.ManyToManyField(to='users.Role'),
        ),
    ]
