# Generated by Django 3.2.8 on 2023-07-25 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(default='', max_length=30)),
                ('num_floors', models.IntegerField(default=1)),
                ('reservations_hidden', models.BooleanField(blank=True, default=False)),
                ('force_hidden', models.BooleanField(blank=True, default=False)),
                ('roles', models.ManyToManyField(blank=True, related_name='building_roles', to='users.Role')),
                ('write_roles', models.ManyToManyField(blank=True, related_name='building_write_roles', to='users.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_num', models.CharField(default='', max_length=5)),
                ('num_rooms', models.IntegerField(default=0)),
                ('color', models.CharField(default='#FF8C00', max_length=7)),
                ('reservations_hidden', models.BooleanField(blank=True, default=False)),
                ('force_hidden', models.BooleanField(blank=True, default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floors.building')),
                ('roles', models.ManyToManyField(blank=True, related_name='floor_roles', to='users.Role')),
                ('write_roles', models.ManyToManyField(blank=True, related_name='floor_write_roles', to='users.Role')),
            ],
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=5)),
                ('closed', models.BooleanField(blank=True, default=False)),
                ('reservations_hidden', models.BooleanField(blank=True, default=False)),
                ('force_hidden', models.BooleanField(blank=True, default=False)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floors.floor')),
                ('roles', models.ManyToManyField(blank=True, related_name='room_roles', to='users.Role')),
                ('write_roles', models.ManyToManyField(blank=True, related_name='room_write_roles', to='users.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_week', models.IntegerField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floors.building')),
                ('friday_hours', models.ManyToManyField(related_name='friday_hours', to='floors.TimeRange')),
                ('monday_hours', models.ManyToManyField(related_name='monday_hours', to='floors.TimeRange')),
                ('saturday_hours', models.ManyToManyField(related_name='saturday_hours', to='floors.TimeRange')),
                ('sunday_hours', models.ManyToManyField(related_name='sunday_hours', to='floors.TimeRange')),
                ('thursday_hours', models.ManyToManyField(related_name='thursday_hours', to='floors.TimeRange')),
                ('tuesday_hours', models.ManyToManyField(related_name='tuesday_hours', to='floors.TimeRange')),
                ('wednesday_hours', models.ManyToManyField(related_name='wednesday_hours', to='floors.TimeRange')),
            ],
        ),
    ]
