# Generated by Django 4.2 on 2023-04-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='reservations',
            field=models.ManyToManyField(blank=True, to='reservations.reservation'),
        ),
    ]
