# Generated by Django 3.2.8 on 2023-04-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0003_alter_floor_floor_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='color',
            field=models.CharField(default='#FF8C00', max_length=7),
        ),
    ]
